name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'terraform/**'
  workflow_dispatch:

env:
  AWS_REGION: 'us-west-2' # Replace with your AWS region
  TF_VERSION: '1.0.0'     # Replace with your Terraform version

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply (Manual Approval)
      run: terraform apply -auto-approve
      working-directory: ./terraform
      if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'

    # Bot deployment steps...

