name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # or any specific version you need

    - name: Change to src directory
      run: cd src

    - name: Install dependencies
      run: npm install
      working-directory: ./src

    - name: Run tests
      run: npm test
      working-directory: ./src
